# Generated by Django 5.2.7 on 2025-10-17 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companie_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=300)),
                ('long_description', models.TextField()),
                ('salary', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schredule', models.CharField(max_length=100)),
                ('Id_Profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.companies')),
            ],
        ),
        migrations.CreateModel(
            name='profils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('seeker', 'Job Seeker'), ('company', 'Company')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='companies',
            name='Id_Profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profils'),
        ),
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('Id_Profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profils')),
            ],
        ),
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=300)),
                ('Id_Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.advertisements')),
                ('Id_Profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.people')),
            ],
        ),
    ]
